language: "en"
early_access: false
reviews:
  high_level_summary: false
  poem: false
  review_status: false
  collapse_walkthrough: true
  changed_files_summary: false
  path_instructions:
    - path: "**/*.mdx"
      instructions: |
        "ALWAYS review Markdown content THOROUGHLY with the following criteria:
        - Use proper nouns in place of personal pronouns like 'We' and 'Our' to maintain consistency in communal documentation.
        - Avoid gender-specific language and use the imperative form.
        - Monitor capitalization for emphasis. Avoid using all caps, italics, or bold for emphasis.
        - Ensure proper nouns are capitalized in sentences.
        - Apply the Oxford comma.
        - Use proper title case for buttons, tab names, page names, and links. Sentence case should be used for body content and short phrases, even in links.
        - Use correct spelling and grammar at all times (IMPORTANT).
        - For H1, H2, and H3 headers:
          1. Use sentence case, capitalizing only the first word.
          2. Preserve the capitalization of proper nouns, technical terms, and acronyms as defined in the 'nouns.txt' file located in the root directory of the project.
          3. Do not automatically lowercase words that appear in the 'nouns.txt' file, regardless of their position in the header.
        - Flag any headers that seem to inconsistently apply these rules for manual review.
        - When reviewing capitalization, always refer to the 'nouns.txt' file for the correct capitalization of proper nouns and technical terms specific to the project.
        "
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "main"
chat:
  auto_reply: true
