/** @format */

import React from 'react';
import { DocsThemeConfig } from 'nextra-theme-docs';
import { useRouter } from 'next/router';
import { useConfig } from 'nextra-theme-docs';
import { FeelbackYesNo, PRESET_LIKE_DISLIKE } from '@feelback/react';
import '@feelback/react/styles/feelback.css';
import { Search } from './components/Search';
import { Footer } from './components/Footer';
import { AskAIButton } from './components/AskAIButton';
import CustomHeader from './components/CustomHeader';
import { useFeature } from '@growthbook/growthbook-react';

const config: DocsThemeConfig = {
  navbar: {
    component: CustomHeader
  },
  darkMode: true,
  // banner: {
  //   key: 'viem/op-stack',
  //   text: (
  //     <a href='/notices/sdk-deprecation'>
  //       🎉 We are deprecating the Optimism SDK and migrating all tutorials to use viem/op-stack.
  //       Read more →
  //     </a>
  //   )
  // },
  docsRepositoryBase: 'https://github.com/ethereum-optimism/docs/blob/main/',
  footer: {
    text: <Footer />
  },

  sidebar: {
    defaultMenuCollapseLevel: 1,
    autoCollapse: true
  },
  toc: {
    backToTop: true,
    extraContent: () => (
      <>
        <hr className='divider top-divider' />
        <FeelbackYesNo
          contentSetId='b2983747-797d-4e6e-9ea3-15d59b9c27ce'
          preset={PRESET_LIKE_DISLIKE}
          textQuestion='Is this page useful?'
          textAnswer='Thanks for your feedback :)'
        />
        <hr className='divider' />
      </>
    )
  },
  navigation: false,
  feedback: {
    content: '❤️ Share general feedback',
    labels: 'user-feedback'
  },
  editLink: {
    text: '✏️ Edit this page on GitHub'
  },
  useNextSeoProps() {
    const { asPath } = useRouter();
    if (asPath !== '/') {
      return {
        titleTemplate: '%s | Optimism Docs'
      };
    }
  },
  head: () => {
    const { asPath, defaultLocale, locale } = useRouter();
    const { frontMatter } = useConfig();
    const url =
      'https://docs.optimism.io' + (defaultLocale === locale ? asPath : `/${locale}${asPath}`);
    const enableDocsAIWidget = useFeature('enable_docs_ai_widget').on;

    return (
      <>
        <meta property='og:url' content={url} />
        <meta property='og:title' content={frontMatter.title || 'Optimism Docs'} />
        <meta
          property='og:description'
          content={frontMatter.description || 'Optimism Docs for developers'}
        />
        <meta property='og:image' content='https://docs.optimism.io/logos/docs-header.png' />
        <meta name='twitter:card' content='summary_large_image' />
        <meta name='twitter:title' content={frontMatter.title || 'Optimism Docs'} />
        <meta
          name='twitter:description'
          content={frontMatter.description || 'Optimism Docs for developers'}
        />
        <meta name='twitter:image' content='https://docs.optimism.io/logos/docs-header.png' />
        <link rel='icon' href='/img/icons/favicon.ico' type='image/x-icon'></link>
        {enableDocsAIWidget && (
          <script
            async
            src='https://widget.kapa.ai/kapa-widget.bundle.js'
            data-website-id={process.env.NEXT_PUBLIC_KAPA_WEBSITE_ID || ''}
            data-project-name='OP Labs'
            data-project-color='#FF0420'
            data-modal-title='Optimism Docs Assistant ✨'
            data-project-logo='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8nhCmw7cu6jVQI01JFtMAV5tkTNLJXMSAOg&s'
            data-modal-example-questions='What is the OP Stack?, How do I get started with Supersim?, How do I create a SuperERC20 token?, How do I get faucet funds?'
            data-user-analytics-fingerprint-enabled='true'
            data-modal-override-open-id='custom-ask-ai-button'
            data-modal-ask-ai-input-placeholder='Ask me a question about building on Optimism'
            data-button-hide='true'
            data-max-tokens='100'
            data-consent-required='true'
            data-consent-screen-disclaimer='This is an AI assistant powered by [kapa.ai](https://www.kapa.ai/). Please be aware that any information, including personal information or sensitive data, shared by you is provided at your own risk and may be accessed by [kapa.ai](https://www.kapa.ai/) and Optimism. Your use is further subject to the [kapa.ai Terms of Service](https://www.kapa.ai/content/terms-of-service) and the [Optimism Terms of Service](https://www.optimism.io/terms). Please note that all responses are generated by AI so remember to use your own judgment.By clicking the “I agree, let’s chat” button, you are confirming your understanding of and agreement with the above.'
            data-modal-disclaimer='This is an AI assistant powered by kapa.ai. Please be aware that any information, including personal information or sensitive data, shared by you herein is provided at your own risk and subject to the kapa.ai [privacy policy](https://www.kapa.ai/content/privacy-policy). Please note that all responses are generated by AI so remember to use your own judgment.'
          ></script>
        )}
      </>
    );
  }
};

export default config;
