name: Suggest an RPC Provider
description: Suggest an RPC provider for developers to use when building with Optimism
title: Suggest an RPC Provider
labels: ["documentation,rpc-provider,community-request"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this suggestion, be sure to read the [listing of current RPC Providers](https://snazzy-hamster-4e1647.netlify.app/tools/rpc-providers).
  - type: markdown
    id: project_info
    attributes:
      value: "## Project Info"
  - type: input
    id: rpc_provider_name
    attributes:
      label: RPC Provider Name
    validations:
      required: true
  - type: textarea
    id: rpc_provider_description
    attributes:
      label: RPC Provider Description & Pricing
    validations:
      required: true
  - type: input
    id: rpc_provider_URL
    attributes:
      label: RPC Provider URL
      description: Please provide the URL for us to link in the project description above.
    validations:
      required: true
  - type: checkboxes
    id: rpc_provider_networks
    attributes:
      label: Supported Networks
      options:
        - label: "OP Mainnet"
          required: false
        - label: "OP Goerli"
          required: false
    validations:
      required: true
  - type: input
    id: rpc_provider_live_date
    attributes:
      label: When did the product go live?
      description: We prioritize products that are battle-tested.
    validations:
      required: true
  - type: dropdown
    id: rpc_provider_open_source
    attributes:
      label: Is the product open source?
      description: We prioritize open source projects when possible.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: rpc_provider_github
    attributes:
      label: GitHub URL
      description: If the project is open source, please provide a link to the product's repo.
  - type: input
    id: rpc_provider_docs
    attributes:
      label: Documentation URL
      description: Please provide a link to the product's technical documentation.
    validations:
      required: true
  - type: textarea
    id: rpc_provider_additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the product here.
  - type: checkboxes
    id: rpc_provider_work_on
    attributes:
      label: Would you like to work on this issue?
      options:
        - label: "Yes"
          required: false
        - label: "No"
          required: false
    validations:
      required: true
