name: Suggest a tutorial
description: Suggest a tutorial to our developers platform
title: "[TUTORIAL] Add PR title"
labels: ["tutorial,documentation,community-request"]
body:
  - type: markdown
    attributes:
      value: |
        We'll consider [our defined content types](https://docs.optimism.io/contribute/style-guide#content-types/) when reviewing the tutorial, so please take a look there first.
  - type: markdown
    id: tutorial_info
    attributes:
      value: "## Tutorial info"
  - type: input
    id: tutorial_title
    attributes:
      label: Tutorial title
      description: What is the title of your tutorial?
    validations:
      required: true
  - type: textarea
    id: tutorial_description
    attributes:
      label: Tutorial description
      description: Summarize what the user should be able to accomplish by following the tutorial
    validations:
      required: true
  - type: input
    id: tutorial_tags
    attributes:
      label: Tutorial tags
      description: What topics are covered in your tutorial? Some examples include 'frontend', 'backend', 'nft', 'security', 'nodes', but feel free to add new ones.
    validations:
      required: true
  - type: dropdown
    id: tutorial_skill_level
    attributes:
      label: Skill level
      options:
        - "Beginner"
        - "Intermediate"
        - "Advanced"
    validations:
      required: true
  - type: dropdown
    id: tutorial_hosted
    attributes:
      label: Hosted on Optimism.io or hosted elsewhere?
      description: Let us know if you want your tutorial to be hosted on the docs.optimism.io website or if it is published elsewhere and you want us to link out to the tutorial
      options:
        - "Hosted on optimism.io"
        - "Hosted elsewhere"
    validations:
      required: true
  - type: textarea
    id: tutorial_content
    attributes:
      label: "For tutorials to be hosted on Optimism.io: Tutorial Content"
      description: Please provide a detailed outline of the content for the tutorial
  - type: input
    id: tutorial_url
    attributes:
      label: "For tutorials hosted elsewhere: URL to tutorial"
      description: Please paste the URL to your tutorial
  - type: textarea
    id: tutorial_additional_context
    attributes:
      label: Additional context
      description: Add additional context or screenshots of the tutorial steps here
