name: Suggest an FAQ item
description: Suggest a FAQ question+answer to help developers when building with Optimism
title: "[FAQ] Add PR title"
labels: ["documentation,faq,community-request"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this suggestion, be sure to read our expectations for [FAQ content](https://docs.optimism.io/contribute/style-guide#faqs). <br> For an example FAQ guide with question+answer pairs, see [Security Model FAQ](https://docs.optimism.io/security/faq#security-model-faq).
  - type: markdown
    id: project_info
    attributes:
      value: "## Project Info"
  - type: dropdown
    id: faq_category
    attributes:
      label: FAQ Category
      description: let us know if you plan to add a new FAQ item (question + answer) or revise an existing item
      options:
        - "Add faq item to an existing page"
        - "Add faq item to a brand new page"
        - "Revise an existing faq item"
    validations:
      required: true
  - type: input
    id: faq_where_should_it_live
    attributes:
      label: What page will this FAQ item live?
      description: list the page where the FAQ (question + answer) would be most relevant on docs.optimism.io
    validations:
      required: true
  - type: textarea
    id: faq_problem
    attributes:
      label: write the question from a developer's perspective
    validations:
      required: true
  - type: textarea
    id: faq_solution
    attributes:
      label: answer the question identified above as best as possible
    validations:
      required: true
  - type: textarea
    id: faq_additional_context
    attributes:
      label: Additional context
      description: Add any additional info or context for the FAQ here
