name: Suggest a troubleshooting item
description: Suggest a troubleshooting problem+solution to help developers when building with Optimism
title: "[TROUBLESHOOTING] Add PR title"
labels: ["documentation,troubleshooting,community-request"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this suggestion, be sure to read our expectations for [troubleshooting content](https://docs.optimism.io/contribute/style-guide#troubleshooting-guides). <br> For an example troubleshooting guide with problem+solution pairs, see [Troubleshooting: L2 Rollup](https://docs.optimism.io/operators/chain-operators/management/troubleshooting).
  - type: markdown
    id: project_info
    attributes:
      value: "## Project Info"
  - type: dropdown
    id: troubleshooting_category
    attributes:
      label: Troubleshooting Category
      description: let us know if you plan to add a new troubleshooting item (problem + solution) or revise an existing item
      options:
        - "Add troubleshooting item to an existing page"
        - "Add troubleshooting item to a brand new page"
        - "Revise an existing troubleshooting item"
    validations:
      required: true
  - type: input
    id: troubleshooting_where_should_it_live
    attributes:
      label: What page will this troubleshooting item live?
      description: list the page where the troubleshooting (problem + solution) would be most relevant on docs.optimism.io
    validations:
      required: true
  - type: textarea
    id: troubleshooting_problem
    attributes:
      label: describe the problem from a developer's perspective, including any error message received
    validations:
      required: true
  - type: textarea
    id: troubleshooting_solution
    attributes:
      label: explain the solution to the problem identified above, use step-by-step instructions when possible
    validations:
      required: true
  - type: textarea
    id: troubleshooting_additional_context
    attributes:
      label: Additional context
      description: Add additional context or screenshots of the reported troubleshooting problem here
