import { Project } from "ts-morph";
import * as fs from "fs";
import * as path from "path";

// Define which components to generate
// Key: Component Name, Value: path to source file
const ACTIONS_COMPONENTS: Record<string, string> = {
  WalletNamespace: "src/wallet/core/namespace/WalletNamespace.ts",
};

interface MethodDoc {
  name: string;
  description: string;
  params: Array<{ name: string; type: string; description: string }>;
  returns: string;
  throws?: string;
  signature: string;
}

function extractMethodDocs(classDeclaration: any): MethodDoc[] {
  const methods: MethodDoc[] = [];

  for (const method of classDeclaration.getMethods()) {
    const jsDoc = method.getJsDocs()[0];
    if (!jsDoc) continue;

    const tags = jsDoc.getTags();
    const description = jsDoc.getDescription().trim();

    const params = tags
      .filter((tag) => tag.getTagName() === "param")
      .map((tag) => {
        // Get full comment text including multi-line descriptions
        const commentText = tag.getComment();
        const text = typeof commentText === 'string'
          ? commentText
          : Array.isArray(commentText)
            ? commentText.map(part => typeof part === 'string' ? part : part.text).join(' ')
            : "";

        const name = tag.compilerNode.name?.getText() || "";
        return {
          name,
          type:
            method
              .getParameters()
              .find((p) => p.getName() === name)
              ?.getType()
              .getText() || "unknown",
          description: text.trim(),
        };
      });

    const returnsTag = tags.find((tag) => tag.getTagName() === "returns");
    const throwsTag = tags.find((tag) => tag.getTagName() === "throws");

    methods.push({
      name: method.getName(),
      description,
      params,
      returns: returnsTag?.getCommentText() || "",
      throws: throwsTag?.getCommentText(),
      signature: method.getText(),
    });
  }

  return methods;
}

function generateComponentMDX(classDescription: string, methods: MethodDoc[]): string {
  let mdx = `{/*
  ⚠️ WARNING: DO NOT EDIT THIS FILE DIRECTLY ⚠️

  This file is auto-generated from the Actions SDK source code.

  To update this documentation:
  1. Bump the SDK version in package.json: pnpm add @eth-optimism/actions-sdk@latest
  2. Run the generation script: pnpm prebuild

  Any manual edits will be overwritten on the next generation.
*/}

`;

  // Add class description if available
  if (classDescription) {
    mdx += `${classDescription}\n\n`;
  }

  // Add table of functions
  if (methods.length > 0) {
    mdx += `## Methods\n\n`;
    mdx += `| Function | Description |\n`;
    mdx += `|----------|-------------|\n`;
    for (const method of methods) {
      const methodLink = `#${method.name.toLowerCase()}`;
      mdx += `| [\`${method.name}()\`](${methodLink}) | ${method.description || ''} |\n`;
    }
    mdx += `\n---\n\n`;
  }

  for (const method of methods) {
    mdx += `### \`${method.name}()\`\n\n`;

    if (method.description) {
      mdx += `${method.description}\n\n`;
    }

    if (method.params.length > 0) {
      mdx += `**Parameters:**\n\n`;
      mdx += `| Parameter | Type | Description |\n`;
      mdx += `|-----------|------|-------------|\n`;
      for (const param of method.params) {
        mdx += `| \`${param.name}\` | \`${param.type}\` | ${param.description} |\n`;
      }
      mdx += `\n`;
    }

    if (method.returns) {
      mdx += `**Returns:** ${method.returns}\n\n`;
    }

    if (method.throws) {
      mdx += `**Throws:** ${method.throws}\n\n`;
    }

    mdx += `---\n\n`;
  }

  return mdx;
}

async function main() {
  console.log("🔍 Looking for Actions SDK...");

  // Find the SDK package in node_modules
  const sdkPath = path.join(
    process.cwd(),
    "node_modules",
    "@eth-optimism",
    "actions-sdk"
  );

  if (!fs.existsSync(sdkPath)) {
    console.error("❌ Actions SDK not found. Please run: pnpm install");
    process.exit(1);
  }

  console.log("✅ Found Actions SDK at:", sdkPath);

  // Create a ts-morph project without tsconfig (published packages don't include it)
  const project = new Project({
    compilerOptions: {
      target: 99, // ESNext
      module: 99, // ESNext
    },
  });

  // Create snippets directory if it doesn't exist
  const snippetsDir = path.join(process.cwd(), "snippets", "actions");
  if (!fs.existsSync(snippetsDir)) {
    fs.mkdirSync(snippetsDir, { recursive: true });
  }

  // Generate docs for each configured API
  for (const [className, sourcePath] of Object.entries(ACTIONS_COMPONENTS)) {
    console.log(`\n📖 Processing ${className}...`);

    const sourceFilePath = path.join(sdkPath, sourcePath);

    if (!fs.existsSync(sourceFilePath)) {
      console.error(`❌ ${sourcePath} not found at: ${sourceFilePath}`);
      continue;
    }

    const sourceFile = project.addSourceFileAtPath(sourceFilePath);
    const classDeclaration = sourceFile.getClass(className);

    if (!classDeclaration) {
      console.error(`❌ ${className} class not found in ${sourcePath}`);
      continue;
    }

    console.log("📝 Extracting class and method documentation...");

    // Extract class description
    const classJsDoc = classDeclaration.getJsDocs()[0];
    const classDescription = classJsDoc ? classJsDoc.getDescription().trim() : '';

    const methods = extractMethodDocs(classDeclaration);

    console.log(`✅ Found ${methods.length} documented methods`);

    // Convert ClassName to kebab-case for filename (WalletNamespace -> wallet-namespace)
    const componentFileName = className
      .replace(/([A-Z])/g, "-$1")
      .toLowerCase()
      .slice(1); // remove leading dash

    // Generate component
    console.log(`🏗️  Generating ${componentFileName}.mdx...`);
    const componentContent = generateComponentMDX(classDescription, methods);

    // Write to snippets directory
    const outputPath = path.join(snippetsDir, `${componentFileName}.mdx`);
    fs.writeFileSync(outputPath, componentContent);

    console.log(`✅ Component generated at: ${outputPath}`);

    console.log("💡 Use it in your docs with:");
    console.log(
      `   import ${className} from '/snippets/actions/${componentFileName}.mdx';`
    );
    console.log(`   <${className} />`);
  }

  console.log("\n🎉 All API docs generated successfully!");
}

main().catch(console.error);
